name: geoguessr
channels:
  - defaults
dependencies:
  - python==3.12.3
  - jupyter
  - ipykernel
  - pip:
    - numpy==2.3.4
    - pandas==2.3.3
    - mapillary==1.0.15
    - urllib3==2.5.0
    - requests==2.32.5
    - python-dotenv==1.2.1
    - mpmath==1.3.0
    - geopandas==1.1.1
    - plotly==6.4.0
    - s2sphere==0.2.5
    - matplotlib==3.10.7
    - pillow==12.0.0
    - tqdm==4.67.1
    - scikit-learn==1.7.2
    - "torch --extra-index-url https://download.pytorch.org/whl/cu124"
    - "torchvision --extra-index-url https://download.pytorch.org/whl/cu124"
